version: '3'
services:
    api:
        build: .
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - db
            - db_test

    db:
        image: "postgres:latest"
        restart: unless-stopped
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: jobs
            POSTGRES_DB: jobs
            POSTGRES_PASSWORD: jobs
        volumes:
            -   db_data:/var/lib/postgresql/data

    db_test:
        image: "postgres:latest"
        restart: unless-stopped
        ports:
            - "5435:5432"
        environment:
            POSTGRES_USER: jobs
            POSTGRES_DB: jobs
            POSTGRES_PASSWORD: jobs

volumes:
    db_data: